name: Create Pull Request to my-neovim-pluginlist

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run RSS fetch script
        run: uv run scripts/fetch_rss.py data/latest_rss.json

      - name: Check RSS data
        run: cat data/latest_rss.json

      - name: Find correct category
        run: jq -r 'map(.title = "https://github.com/" + .title) | .[].title' data/latest_rss.json | xargs -i uv run scripts/search.py {} | tee data/search.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR doc
        run: cat data/search.json | uv run scripts/predict_category.py | tee data/pr.md
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Checkout my-neovim-pluginlist
        uses: actions/checkout@v4
        with:
          repository: yutkat/my-neovim-pluginlist
          path: data/my-neovim-pluginlist
          fetch-depth: 0

      - name: Insert New plugin
        run: cat data/pr.md | ./scripts/edit_pluginlist.sh

      - name: Update table style
        run: |
          {
            echo "|URL|Category|Reason|"
            echo "|---|---|---|"
            cat data/pr.md
          } | tee data/pr-with-header.md

      - name: Create Pull Request on my-neovim-pluginlist
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          path: data/my-neovim-pluginlist
          commit-message: "Add"
          committer: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: ai-${{ github.run_id }}-${{ github.run_attempt }}
          delete-branch: true 
          base: main
          title: "Add"
          body-path: "data/pr-with-header.md"
          labels: "automated pr, bot"
