name: Fetch RSS Data

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  fetch_rss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv install

      - name: Run RSS fetch script
        run: uv run scripts/fetch_rss.py data/latest_rss.json

      - name: Check RSS data
        run: cat data/latest_rss.json

      - name: Find correct category
        run: jq -r 'map(.title = "https://github.com/" + .title) | .[].title' data/latest_rss.json | xargs -i uv run scripts/search.py {} > data/search.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find correct category
        run: cat data/search.json | uv run scripts/predict_category.py > data/pr.md
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

