name: Vector DB Daily Update

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_vector_db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout my-neovim-pluginlist
        uses: actions/checkout@v4
        with:
          repository: yutkat/my-neovim-pluginlist
          path: data/my-neovim-pluginlist
          fetch-depth: 0

      - name: Install required system dependencies
        run: sudo apt-get update && sudo apt-get install -y libomp-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Create a list to update
        run: git log -p --since='1 day ago' --grep=Add -i --diff-filter=AM | grep '^+-' | grep -v '^+++' | sed 's/^+//g' | sed -E 's#^.*\]\((https://github\.com/[^)]+)\).*$#\1#' | tee ../update-list.txt
        working-directory: data/my-neovim-pluginlist/

      - name: Run convert script
        run: uv run scripts/convert_to_csv.py data/update-list.csv data/my-neovim-pluginlist data/update-list.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create csv
        run: |
          echo "URL,category,readme" > data/neovim-plugin-category.csv
          awk 'FNR > 1' data/update-list.csv >> data/neovim-plugin-category.csv

      - name: embedding
        run: uv run scripts/embedding.py data/neovim-plugin-category.csv
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit chroma_db changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update chroma_db data"
          file_pattern: chroma_db/**

